
SLOT_PER_FRAME = 20
SLOT_PER_SUBFRAME = 2
MAX_SUBFRAME_PER_FRAME = 10
MAX_FRAME_NUM = 1024
MAX_SUBFRAME = MAX_FRAME_NUM * MAX_SUBFRAME_PER_FRAME
MAX_TTI_TIME = SLOT_PER_FRAME * MAX_FRAME_NUM

VERSION = "V1.2"
QUERY_DRX_CLIENT_STATE = "0x000000000001"


FILE = "./data/cliendData.csv"

# ONDURATION_VALUE = 0.1
# INACTIVITY_VALUE = 0.3
# ULRETX_VALUE = 0.5
# DLRETX_VALUE = 0.7
# ACTIVE_VALUE = 0.9

ONDURATION_VALUE = 0.9
INACTIVITY_VALUE = 0.7
ULRETX_VALUE = 0.5
DLRETX_VALUE = 0.3
ACTIVE_VALUE = 0.1

