# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoSubmitDailyReport.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(315, 300)
        Form.setMaximumSize(QtCore.QSize(315, 300))
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(210, 250, 81, 23))
        self.pushButton_start.setObjectName("pushButton_start")
        self.X_lcdNumber = QtWidgets.QLCDNumber(Form)
        self.X_lcdNumber.setGeometry(QtCore.QRect(120, 30, 64, 20))
        self.X_lcdNumber.setDigitCount(5)
        self.X_lcdNumber.setProperty("intValue", 0)
        self.X_lcdNumber.setObjectName("X_lcdNumber")
        self.Y_lcdNumber = QtWidgets.QLCDNumber(Form)
        self.Y_lcdNumber.setGeometry(QtCore.QRect(190, 30, 64, 20))
        self.Y_lcdNumber.setObjectName("Y_lcdNumber")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 101, 20))
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 271, 141))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 40, 61, 20))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 70, 61, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 100, 61, 20))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(180, 20, 21, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_web_x = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_web_x.setGeometry(QtCore.QRect(100, 40, 64, 20))
        self.lineEdit_web_x.setObjectName("lineEdit_web_x")
        self.lineEdit_web_y = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_web_y.setGeometry(QtCore.QRect(170, 40, 64, 20))
        self.lineEdit_web_y.setObjectName("lineEdit_web_y")
        self.lineEdit_submit_y = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_submit_y.setGeometry(QtCore.QRect(170, 70, 64, 20))
        self.lineEdit_submit_y.setObjectName("lineEdit_submit_y")
        self.lineEdit_submit_x = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_submit_x.setGeometry(QtCore.QRect(100, 70, 64, 20))
        self.lineEdit_submit_x.setObjectName("lineEdit_submit_x")
        self.lineEdit_ok_y = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ok_y.setGeometry(QtCore.QRect(170, 100, 64, 20))
        self.lineEdit_ok_y.setObjectName("lineEdit_ok_y")
        self.lineEdit_ok_x = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ok_x.setGeometry(QtCore.QRect(100, 100, 64, 20))
        self.lineEdit_ok_x.setObjectName("lineEdit_ok_x")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(60, 220, 111, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_delay = QtWidgets.QLineEdit(Form)
        self.lineEdit_delay.setGeometry(QtCore.QRect(190, 220, 64, 20))
        self.lineEdit_delay.setObjectName("lineEdit_delay")
        self.label_state = QtWidgets.QLabel(Form)
        self.label_state.setGeometry(QtCore.QRect(10, 280, 301, 20))
        self.label_state.setObjectName("label_state")
        self.checkBox_keepDesktopAlive = QtWidgets.QCheckBox(Form)
        self.checkBox_keepDesktopAlive.setGeometry(QtCore.QRect(40, 250, 131, 23))
        self.checkBox_keepDesktopAlive.setChecked(True)
        self.checkBox_keepDesktopAlive.setObjectName("checkBox_keepDesktopAlive")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "日报自动提交工具"))
        self.pushButton_start.setText(_translate("Form", "开始"))
        self.label_4.setText(_translate("Form", "鼠标实时坐标："))
        self.groupBox.setTitle(_translate("Form", "设置坐标"))
        self.label.setText(_translate("Form", "网页坐标："))
        self.label_5.setText(_translate("Form", "提交坐标："))
        self.label_6.setText(_translate("Form", "确认坐标："))
        self.label_2.setText(_translate("Form", "X:"))
        self.label_3.setText(_translate("Form", "Y:"))
        self.lineEdit_web_x.setText(_translate("Form", "0"))
        self.lineEdit_web_y.setText(_translate("Form", "0"))
        self.lineEdit_submit_y.setText(_translate("Form", "0"))
        self.lineEdit_submit_x.setText(_translate("Form", "0"))
        self.lineEdit_ok_y.setText(_translate("Form", "0"))
        self.lineEdit_ok_x.setText(_translate("Form", "0"))
        self.label_7.setText(_translate("Form", "延迟时间(分钟)："))
        self.lineEdit_delay.setText(_translate("Form", "0"))
        self.label_state.setText(_translate("Form", "日报自动提交工具"))
        self.checkBox_keepDesktopAlive.setText(_translate("Form", "保持桌面不锁屏"))

