
SLOT_PER_FRAME = 20

# ONDURATION_VALUE = 0.1
# INACTIVITY_VALUE = 0.3
# ULRETX_VALUE = 0.5
# DLRETX_VALUE = 0.7
# ACTIVE_VALUE = 0.9

ONDURATION_VALUE = 0.9
INACTIVITY_VALUE = 0.7
ULRETX_VALUE = 0.5
DLRETX_VALUE = 0.3
ACTIVE_VALUE = 0.1

